server:
  port: 8080
spring:
  h2:
    console:
      enabled: true

  datasource:
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;

  jpa:
    hibernate:
      ddl-auto: none

