CREATE TABLE item
(
    id         BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '상품 고유번호',
    name       VARCHAR(50) NOT NULL COMMENT '상품 이름',
    created_at DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시간',
    updated_At DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시간'
);


CREATE TABLE mock_item
(
    id         BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '상품 고유번호',
    name       VARCHAR(50) NOT NULL COMMENT '상품 이름',
    created_at DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시간',
    updated_At DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시간'
);